const DASHBOARD_ACTION_TYPES = {
    DASHBOARD_INITIATE: 'DASHBOARD_INITIATE',
    DASHBOARD_FAILED: 'DASHBOARD_FAILED',
    DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
}

export default DASHBOARD_ACTION_TYPES;