const CREATE_DATA_ACTION_TYPES = {
    CREATE_DATA_INITIATE: 'CREATE_DATA_INITIATE',
    CREATE_DATA_FAILED: 'CREATE_DATA_FAILED',
    CREATE_DATA_SUCCESS: 'CREATE_DATA_SUCCESS',
}

export default CREATE_DATA_ACTION_TYPES;