const CHART_WIDGET_ACTION_TYPES = {
     CHART_WIDGET_ADD_PROCESS: 'CHART_WIDGET_ADD_PROCESS',
     CHART_WIDGET_GET_PROCESS: 'CHART_WIDGET_GET_PROCESS',
     CHART_WIDGET_DELETE_PROCESS: 'CHART_WIDGET_DELETE_PROCESS',
     CHART_WIDGET_UPDATE_PROCESS: 'CHART_WIDGET_UPDATE_PROCESS',
     CHART_WIDGET_RESET_PROCESS: 'CHART_WIDGET_RESET_PROCESS',
}

export default CHART_WIDGET_ACTION_TYPES;