const SUMMERY_WIDGET_ACTION_TYPES = {
     SUMMERY_WIDGET_ADD_PROCESS: 'SUMMERY_WIDGET_ADD_PROCESS',
     SUMMERY_WIDGET_GET_PROCESS: 'SUMMERY_WIDGET_GET_PROCESS',
     SUMMERY_WIDGET_DELETE_PROCESS: 'SUMMERY_WIDGET_DELETE_PROCESS',
     SUMMERY_WIDGET_UPDATE_PROCESS: 'SUMMERY_WIDGET_UPDATE_PROCESS',
     SUMMERY_WIDGET_RESET_PROCESS: 'SUMMERY_WIDGET_RESET_PROCESS',
}

export default SUMMERY_WIDGET_ACTION_TYPES;